---
abstract: 'Subclassable and hostless URIs'
author:
  - 'Rafael Kitover, C<< <rkitover at cpan.org> >>'
  - 'Rafael Kitover <rkitover@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: URI-SmartURI
no_index:
  directory:
    - inc
    - t
provides:
  URI::SmartURI:
    file: lib/URI/SmartURI.pm
    version: 0.031
requires:
  Class::C3::Componentised: 0
  File::Find::Rule: 0
  List::MoreUtils: 0
  List::Util: 0
  Moose: 0
  Scalar::Util: 0
  URI: 1.51
  namespace::clean: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/rkitover/uri-smarturi.git
version: 0.031
